initial changes

diff --git a/dist-assets/pkg-scripts/preinstall b/dist-assets/pkg-scripts/preinstall
--- a/dist-assets/pkg-scripts/preinstall
+++ b/dist-assets/pkg-scripts/preinstall
@@ -10,7 +10,7 @@ INSTALL_DIR=$2
 #
 # TODO: This can be reverted when the following issue has been fixed:
 # https://github.com/electron-userland/electron-builder/issues/8166
-if [[ $INSTALL_DIR == *"Mullvad VPN.app" ]]; then
+if [[ $INSTALL_DIR == *"Thevad VPN.app" ]]; then
     exit 0
 fi
 
@@ -23,7 +23,7 @@ exec > $LOG_DIR/preinstall.log 2>&1
 echo "Running preinstall at $(date)"
 
 # Stop the existing daemon
-"$INSTALL_DIR/Mullvad VPN.app/Contents/Resources/mullvad-setup" prepare-restart &>/dev/null || \
+"$INSTALL_DIR/Thevad VPN.app/Contents/Resources/mullvad-setup" prepare-restart &>/dev/null || \
     echo "Failed to send 'prepare-restart' command to old mullvad-daemon"
 
 # NOTE: This path must be kept in sync with the path defined
@@ -48,4 +48,4 @@ rm "$NEW_CACHE_DIR/relays.json" || true
 rm "$NEW_CACHE_DIR/api-ip-address.txt" || true
 
 # Kill the GUI before proceeding with the upgrade.
-pkill -x "Mullvad VPN" && sleep 1 || echo "Unable to kill GUI, not running?"
+pkill -x "Thevad VPN" && sleep 1 || echo "Unable to kill GUI, not running?"
